server:
  port: 8081
spring:
  main:
    jvm-arguments: --add-opens java.base/java.lang.invoke=ALL-UNNAMED
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hmdp-mysql:3306/hmdp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
#    host: 192.168.100.137
    host: hmdp-redis
    port: 6379
    password: 12345678
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
dianping:
  alioss:
    access-key-id: ${ACCESS_ALIOSS_KEY_ID}
    access-key-secret: ${ACCESS_ALIOSS_KEY_SECRET}
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    region: cn-chengdu
    bucket-name: dianping123